apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo
  namespace: {{ .Values.NAMESPACE }}
spec:
  selector:
    matchLabels:
      app: otel-demo
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: otel-demo
    spec:
      containers:
      - name: otel-demo
        image: {{ print .Values.REPO_NAME "/otel-demo:" .Values.COMMIT_VERSION }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        env:
        - name: DEMO_OTEL_COLLECTOR_ENDPOINT
          value: {{ .Values.OTEL_COLLECTOR_ENDPOINT }}        
---
apiVersion: v1
kind: Service
metadata:
  name: otel-demo-svc
  namespace: {{ .Values.NAMESPACE }}
spec:
  selector:
    app: otel-demo
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer 
