apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel-system
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      batch:

    extensions:
      health_check:

    exporters:
      debug:
        verbosity: detailed

      azuremonitor:
        endpoint: "https://dc.services.visualstudio.com/v2/track"
        instrumentation_key: {{ .Values.APP_INSIGHTS_KEY }}
        maxbatchsize: 100
        maxbatchinterval: 10s
    
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug,azuremonitor]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug,azuremonitor]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug,azuremonitor]
