apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel-system
data:
  otel-collector-config.yaml: |
    receivers:
        zipkin:
            endpoint: 0.0.0.0:9411
    extensions:
        health_check:
        pprof:
            endpoint: :1888
        zpages:
            endpoint: :55679
    exporters:
        #otlp:
        #   endpoint: "jaeger:4317"
        #   tls:
        #       insecure: true
        
        logging:
            loglevel: debug
        #   prometheus:
        #       endpoint: "otelcol:9464"
        #       resource_to_telemetry_conversion:
        #           enabled: true
        #       enable_open_metrics: true

        azuremonitor:
            endpoint: "https://dc.services.visualstudio.com/v2/track"
            instrumentation_key: {{ .Values.APP_INSIGHTS_KEY }}
            maxbatchsize: 100
            maxbatchinterval: 10s
    service:
        extensions: [pprof, zpages, health_check]
        pipelines:
            traces:
                receivers: [zipkin]
                exporters: [azuremonitor,logging]
            metrics:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [azuremonitor,logging]
            logs:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [azuremonitor,logging]
