apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel-system
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

      zipkin:
        endpoint: 0.0.0.0:9411

    processors:
      batch:

    extensions:
      health_check:

    exporters:
      debug:
        verbosity: detailed

      azuremonitor:
        connection_string: {{ .Values.APP_INSIGHTS.CONNECTION_STRING | quote }}
        maxbatchsize: 100
        maxbatchinterval: 10s
    
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp,zipkin]
          processors: [batch]
          exporters: [debug,azuremonitor]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug,azuremonitor]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug,azuremonitor]
