apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
  namespace: simple
  labels:
    app: simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      serviceAccountName: default-sa-identity 
      containers:
        - name: simple
          image: bjd145/simple:f299c36fa3d19428f15c359e6437aca13fdcb335
          ports:
            - containerPort: 5501
          securityContext:
            allowPrivilegeEscalation: false  
            runAsUser: 1000       
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            limits:
              memory: "512Mi"
              cpu: "2"
            requests:
              memory: "64Mi"
              cpu: "0.25"