---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-identity
  namespace: simple
  annotations:
    azure.workload.identity/client-id: client_id
    azure.workload.identity/tenant-id: tenant_id
  labels:
    azure.workload.identity/use: "true"