FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app/api
COPY otel-demo.csproj .
RUN dotnet restore 
COPY . .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0-jammy-chiseled
WORKDIR /app
COPY --from=build-env /app/api/out .
ENTRYPOINT ["/app/otel-demo"]