version: '3'

includes:
  infra:
    taskfile: ./infrastructure/Taskfile.yaml
    dir: ./infrastructure/
    optional: true

tasks:
  up:
    desc: Creates the complete Azure environment
    cmds:
    - task: infra:up 

  status:
    desc: Displays current Kubevela status
    cmds:
    - task: vela system info
