---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/api-id: upbound/v1beta1
  labels:
    meta.upbound.io/rg-name: crossplane-demo-rg
  name: crossplane-demo-rg
spec:
  providerConfigRef:
    name: azure
  forProvider:
    location: SouthCentral US
---
apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/api-id: upbound/v1beta1
  labels:
    meta.upbound.io/rg-name: crossplane-demo-rg
    meta.upbound.io/vnet-name: crossplane-vnet
  name: crossplane-vnet
spec:
  providerConfigRef:
    name: azure
  forProvider:
    addressSpace:
      - 10.183.0.0/16
    location: SouthCentral US
    resourceGroupNameRef:
      name: crossplane-demo-rg
---
apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: private-endpoints
spec:
  providerConfigRef:
    name: azure
  forProvider:
    addressPrefixes:
      - 10.183.1.0/24
    resourceGroupNameRef:
      name: crossplane-demo-rg
    virtualNetworkNameSelector:
      matchLabels:
        meta.upbound.io/vnet-name: crossplane-vnet
---
apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: kubernetes
spec:
  providerConfigRef:
    name: azure
  forProvider:
    addressPrefixes:
      - 10.183.2.0/24
    resourceGroupNameRef:
      name: crossplane-demo-rg
    virtualNetworkNameSelector:
      matchLabels:
        meta.upbound.io/vnet-name: crossplane-vnet
---
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  labels:
    meta.upbound.io/rg-name: crossplane-demo-rg
    meta.upbound.io/aks-name: aks02
  name: aks02
spec:
  providerConfigRef:
    name: azure
  forProvider:
    nodeResourceGroup: aks02_node_rg
    azurePolicyEnabled: true
    oidcIssuerEnabled: true
    workloadIdentityEnabled: true
    localAccountDisabled: true
    azureActiveDirectoryRoleBasedAccessControl:
    - azureRbacEnabled: true 
      managed: true
    defaultNodePool:
      - name: default
        nodeCount: 1
        vnetSubnetIdRef:
          name: kubernetes
        vmSize: Standard_D2_v2
        minCount: 3
        maxCount: 9
        maxPods: 40
        osDiskSizeGb: 30
        osSku: CBLMariner
    dnsPrefix: aks02
    kubernetesVersion: "1.24.6"
    networkProfile:
    - dnsServiceIp: "100.99.0.10"
      dockerBridgeCidr: 172.17.0.1/16
      loadBalancerSku: standard
      networkPlugin: azure
      serviceCidr: 100.99.0.0/16
    identity:
      - type: SystemAssigned
    location: SouthCentral US
    resourceGroupNameRef:
      name: crossplane-demo-rg
  writeConnectionSecretToRef:
    namespace: upbound-system
    name: aks01
---
#apiVersion: azure.crossplane.io/v1alpha3
#kind: ResourceGroup
#metadata:
#  name: crossplane-demo-rg
#spec:
#  location: SouthCentral US
#  providerConfigRef:
#    name: azure
#---
#apiVersion: network.azure.crossplane.io/v1alpha3
#kind: VirtualNetwork
#metadata:
#  name: crossplane-vnet
#spec:
#  resourceGroupNameRef:
#    name: crossplane-demo-rg
#  location: SouthCentral US
#  properties:
#    addressSpace:
#      addressPrefixes:
#        - 10.183.0.0/16
#  providerConfigRef:
#    name: azure
#---
#apiVersion: network.azure.crossplane.io/v1alpha3
#kind: Subnet
#metadata:
#  name: kubernetes
#spec:
#  resourceGroupNameRef:
#    name: crossplane-demo-rg
#  virtualNetworkNameRef:
#    name: crossplane-vnet
#  properties:
#    addressPrefix: 10.183.2.0/24
#  providerConfigRef:
#    name: azure
#---
#apiVersion: network.azure.crossplane.io/v1alpha3
#kind: Subnet
#metadata:
#  name: private-endpoints
#spec:
#  resourceGroupNameRef:
#    name: crossplane-demo-rg
#  virtualNetworkNameRef:
#    name: crossplane-vnet
#  properties:
#    addressPrefix: 10.183.1.0/24
#  providerConfigRef:
#    name: azure
#---
#apiVersion: compute.azure.crossplane.io/v1alpha3
#kind: AKSCluster
#metadata:
#  name: aks01
#spec:
#  resourceGroupNameRef:
#    name: crossplane-demo-rg
#  vnetSubnetIDRef:
#    name: kubernetes
#  location: SouthCentral US
#  version: "1.24.6"
#  nodeCount: 1
#  nodeVMSize: Standard_B2s
#  dnsNamePrefix: aks01
#  disableRBAC: false
#  providerConfigRef:
#    name: azure
#  writeConnectionSecretToRef:
#    namespace: crossplane-system
#    name: aks01
