apiVersion: containers.bjdazure.tech/v1alpha1
kind: AKSCluster
metadata:
  namespace: default
  name: bjdaks04
spec:
  compositionRef:
    name: xcluster-dev
  parameters:
    location: southcentralus
    name: bjdaks04
    nodeCount: 2

