---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: claims
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
  path: ./crossplane/cluster-configs/management/upbound-providers-claims
  prune: true
  validation: client