---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: httpbin-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/httpbin
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
  validation: client