apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://flagger.app
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger-release
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: istio-system
  chart:
    spec:
      chart: flagger
      version: '1.20.0'
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      interval: 1m
  values:
    meshProvider: istio
    metricsServer: http://prometheus.istio-system:9090