apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: clippy-bjdcsa.cloud
  namespace: ingress-nginx
spec:
  secretName: clippy-bjdcsa-cloud-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: clippy.bjdcsa.cloud
  dnsNames:
  -  clippy.bjdcsa.cloud
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - clippy.bjdcsa.cloud
